---
- name: Get existing team
  ansible.builtin.uri:
    url: "{{ ingress_protocol }}://mattermost.{{ ingress_domain }}/api/v4/teams/name/{{ mm_team_name }}"
    method: GET
    status_code: [200, 404, 400]
    headers:
      Authorization: "Bearer {{ mm_admin_token | default(mm_token) }}"
  register: mm_team_get_raw

- block:
    - name: Create new team
      ansible.builtin.uri:
        url: "{{ ingress_protocol }}://mattermost.{{ ingress_domain }}/api/v4/teams"
        method: POST
        body:
          name: "{{ mm_team_name }}"
          display_name: "{{ mm_team_display_name | default(mm_team_name) }}"
          type: "O" # "O" = Open, "I" = Invite only
        status_code: 201
        body_format: json
        headers:
          Authorization: "Bearer {{ mm_admin_token | default(mm_token) }}"
      register: mm_team_post_raw

    - name: Set team ID if new team is created
      ansible.builtin.set_fact:
        mm_team_id: "{{ mm_team_post_raw.json.id }}"
      when: mm_team_post_raw.status == 201
  when: mm_team_get_raw.status in [404, 400]

- name: Set team ID if team exists
  ansible.builtin.set_fact:
    mm_team_id: "{{ mm_team_get_raw.json.id }}"
  when: mm_team_get_raw.status == 200