- name: Source Mattermost admin secret
  kubernetes.core.k8s_info:
    kind: Secret
    name: "mattermost-admin"
    namespace: "{{ mattermost_namespace }}"
  register: mattermost_secret_data

- name: Set secrets facts
  set_fact:
    mattermost_username: "{{ mattermost_secret_data.resources[0].data.mattermost_username | b64decode }}"
    mattermost_password: "{{ mattermost_secret_data.resources[0].data.mattermost_password | b64decode }}"
  when: mattermost_secret_data is defined and mattermost_secret_data.resources[0] is defined