# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- op: add
  path: /spec/template/metadata/labels/app.kubernetes.io~1version
  value: "1.0.0"

- op: add
  path: /spec/template/metadata/labels/app.kubernetes.io~1part-of
  value: easytrade

- op: add
  path: /spec/template/metadata/labels/dt.owner
  value: srg-easytrade-staging

- op: add
  path: /spec/template/spec/containers/0/env/-
  value: 
    name: DT_RELEASE_VERSION
    valueFrom:
      fieldRef:
        fieldPath: metadata.labels['app.kubernetes.io/version']
- op: add
  path: /spec/template/spec/containers/0/env/-
  value: 
    name: DT_RELEASE_PRODUCT
    valueFrom:
      fieldRef:
        fieldPath: metadata.labels['app.kubernetes.io/part-of']
- op: add
  path: /spec/template/spec/containers/0/env/-
  value: 
    name: DT_RELEASE_BUILD_VERSION
    value: "1.0.0-0eec578c"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value: 
    name: DT_RELEASE_STAGE
    value: "staging"